import Anthropic from '@anthropic-ai/sdk';
import { z } from 'zod';

const replySchema = z.object({
  text: z.string().min(1).max(2000),
});

const FALLBACK_REPLY = "I'm not sure about that — please check our help centre for accurate information.";

export async function POST(request) {
  try {
    const a = new Anthropic();
    const msg = await a.messages.create({
      model: 'claude-3',
      max_tokens: 500,
      messages: [],
    });

    const rawText = msg.content[0].text;

    // Confidence: treat very short or empty responses as uncertain
    if (!rawText || rawText.trim().length < 10) {
      return NextResponse.json({
        reply: FALLBACK_REPLY,
        disclaimer: 'This response was generated by AI and may not be fully accurate.',
        fallback: true,
      });
    }

    // Validation: parse against schema before sending to user
    const parsed = replySchema.safeParse({ text: rawText.trim() });
    if (!parsed.success) {
      return NextResponse.json({
        reply: FALLBACK_REPLY,
        disclaimer: 'This response was generated by AI and may not be fully accurate.',
        fallback: true,
      });
    }

    return NextResponse.json({
      reply: parsed.data.text,
      disclaimer: 'This response was generated by AI and may not be fully accurate.',
    });
  } catch (error) {
    // Error isolation: AI errors never surface as 500s
    return NextResponse.json({
      reply: FALLBACK_REPLY,
      disclaimer: 'This response was generated by AI and may not be fully accurate.',
      fallback: true,
    });
  }
}
